### ISSUE TITLE
"enviroment sonoff error "when compile in platfomIO

### ISSUE THREAD

**Issue by alolivas** [lobocobra/sonoff-shutter#5]
Dear all,
First, thanks a lot for doing this custom firmaware. I think this should be a standard feature of the Tasmota firmware by the way, I am surprised that it is not done yet.

I've built the standard Tasmota 6.3 in my environment (ubuntu running PlatformIO) without any issues, but when I try to build this branch I get a:

 Environment sonoff              [ERROR]

I am 100% new to Tasmota, I've done some arduino coding but far more basic than this. To be honest I am just compiling because there is not a binary release of the project, otherwise I would use that instead.

Any idea why it could be firing the error?

Alfonso.

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x ] Hardware used : 
- [ ] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE
```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by localhost61** [comment]
Look at platformio.ini in the project root. The environments are defined here, maybe a misplaced ";" that comment out a needed "define".

**Comment by alolivas** [comment]
Thanks for the quick response. I did not have any luck in finding the issue, however I found a build uploaded by Lobocobra in the Tasmota github page:
https://github.com/arendst/Sonoff-Tasmota/issues/824#issuecomment-412347831
and took it from there.
Thanks!
p.s. it would be great if you could add a release in the repository for useless people like me :)
